### ISSUE TITLE
Access propTypes from prop-types package from NPM instead of main React package

### ISSUE THREAD

**Issue by nicklassvendsrud** [gokulkrishh/react-material-snackbar#6]
The component/React throws this console warning, and should be fixed:

> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by gokulkrishh** [comment]
@nicklassvendsrud Upgraded react to 16 with prop type fixes in **v3.0.1**.

**Comment by gokulkrishh** [comment]
Closing this in regards to above comment :)
